### ISSUE TITLE
JCropImageField removed from models. How to install?

### ISSUE THREAD

**Issue by robertour** [mauler/django-jcrop#1]
Your documentation ask to add this to the model.

```
from django_jcrop.models import JCropImageField
```

However JCropImageField doesn't exist anymore in your models.py.

What should I do instead?

Thanks!

**Comment by mauler** [comment]
That is not good.

Some merge removed this class. I will add it again.

**Comment by mauler** [comment]
Fixed.

**Comment by robertour** [comment]
Cheers!
